---
title: "data dictionary"
author: "Alpha Lu(yl3963)"
date: "11/20/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

FIELD NAME                            |             DESCRIPTION
-----------------------------------|     -----------------------
CASE_NUMBER     |Unique identifier assigned to each application     submitted for processing to the Chicago National                  Processing Center.
CASE_STATUS     |Status associated with the last significant event  or decision. Valid values include “Certified,”    “Certified-Withdrawn,” Denied,” and “Withdrawn”.
CASE_SUBMITTED  |Date and time the application was submitted.
DECISION_DATE   |Date on which the last significant event or        decision was recorded by the Chicago National        Processing Center.
VISA_CLASS      |Indicates the type of temporary application      submitted for processing. Values include H-1B, E-3              Australian, H-1B1 Chile, and H-1B1 Singapore
EMPLOYMENT_START_DATE| Beginning date of employment.
EMPLOYMENT_END_DATE|  Ending date of employment.
EMPLOYER_NAME   |Name of employer submitting labor condition application.
EMPLOYER_BUSINESS_DBA |Trade Name or dba name of employer submitting labor condition application, if applicable.
EMPLOYER_ADDRESS|
EMPLOYER_CITY   |
EMPLOYER_STATE  |
EMPLOYER_POSTAL_CODE           |Contact information of the Employer requesting temporary labor certification.
EMPLOYER_COUNTRY|
EMPLOYER_PROVINCE        |
EMPLOYER_PHONE  |
EMPLOYER_PHONE_EXT            |
AGENT_REPRESENTING_EMPLOYER |Y = Employer is represented by an Agent or  Attorney; N = Employer is not represented by an Agent or Attorney.
AGENT_ATTORNEY_NAME           |Name of Agent or Attorney filing an H-1B         application on behalf of the employer.
AGENT_ATTORNEY_CITY           |City information for the Agent or Attorney filing an H-1B application on behalf of the employer.
AGENT_ATTORNEY_STATE           |State information for the Agent or Attorney filing an H-1B application on behalf of the employer.
JOB_TITLE       |Title of the job.
SOC_CODE        |Occupational code associated with the job being requested for temporary labor condition, as                   classified by the Standard Occupational Classification (SOC) System.
SOC_NAME        |Occupational name associated with the SOC_CODE.
NAICS_CODE      |Industry code associated with the employer requesting permanent labor condition, as classified by the North American Industrial Classification System (NAICS).
TOTAL_WORKERS |Total number of foreign workers requested by the Employer(s).
NEW_EMPLOYMENT |Indicates requested worker(s) will begin employment for new employer, as defined by USCIS I-29.
CONTINUED_EMPLOYMENT |Indicates requested worker(s) will be continuing employment with same employer, as defined by USCIS I-29.
CHANGE_PREVIOUS_EMPLOYMENT | Indicates requested worker(s) will be continuing employment with same employer without material change to job duties, as defined by USCIS I-29.
NEW_CONCURRENT_EMPLOYMENT  |Indicates requested worker(s) will begin employment with additional employer, as defined by USCIS I-29.
CHANGE_EMPLOYER |Indicates requested worker(s) will begin employment for new employer, using the same classification currently held, as defined by USCIS I-29.
AMENDED_PETITION | Indicates requested worker(s) will be continuing employment with same employer with material change to job duties, as defined by USCIS I-29.
FULL_TIME_POSITION | Y = Full Time Position; N = Part Time Position.
PREVAILING_WAGE |Prevailing Wage for the job being requested for temporary labor condition.
PW_UNIT_OF_PAY | Unit of Pay. Valid values include “Daily (DAI),” “Hourly (HR),” “Bi-weekly (BI),” “Weekly (WK),” “Monthly (MTH),” and “Yearly (YR)”.
PW_WAGE_LEVEL |Variables include "I", "II", "III", "IV" or "N/A."
PW_SOURCE |Variables include "OES", "CBA", "DBA", "SCA" or "Other".
PW_SOURCE_YEAR | Year the Prevailing Wage Source was Issued.
PW_SOURCE_OTHER | If "Other Wage Source", provide the source of wage.
WAGE_RATE_OF_PAY_FROM  |Employer’s proposed wage rate.
WAGE_RATE_OF_PAY_TO  |Maximum proposed wage rate.
WAGE_UNIT_OF_PAY  |Unit of pay. Valid values include “Hour", "Week", "Bi-Weekly", "Month", or "Year".
H-1B_DEPENDENT |Y = Employer is H-1B Dependent; N = Employer is not H-1B Dependent.
WILLFUL_VIOLATOR |Y = Employer has been previously found to be a Willful Violator; N = Employer has not been considered a Willful Violator.
SUPPORT_H1B |Y = Employer will use the temporary labor condition application only to support H-1B petitions or extensions of status of exempt H-1B worker(s); N = Employer will not use the temporary labor condition application to support H-1B petitions or extensions of status for exempt H-1B worker(s);N/A = not applicable.
LABOR_CON_AGREE |Y = Employer agrees to the responses to the Labor Condition Statements as in the subsection; N = Employer does not agree to the responses to the Labor Conditions Statements in the subsection.
PUBLIC_DISCLOSURE_LOCATION| Variables include "Place of Business" or "Place of Employment."
WORKSITE_CITY |City information of the foreign worker's intended area of employment.
WORKSITE_COUNTY |County information of the foreign worker's intended area of employment.
WORKSITE_STATE |State information of the foreign worker's intended area of employment.
WORKSITE_POSTAL_CODE | Zip Code information of the foreign worker's intended area of employment.
ORIGINAL_CERT_DATE |Original Certification Date for a Certified_Withdrawn application.

